### ISSUE TITLE
v1.2.1 is not avaiable on packagist.org

### ISSUE THREAD

**Issue by TangRufus** [spatie/image-optimizer#102]
[v1.2.1](https://github.com/spatie/image-optimizer/blob/c2e74a7cd0e23bb9d9ae6b48a9ec00028ef10629/CHANGELOG.md#121---2019-11-23) is not avaiable on [packagist.org](https://packagist.org/packages/spatie/image-optimizer).

Perhaps `git tag && git push --tags` was forgotten?

**Comment by freekmurze** [comment]
Thanks for bringing this to my attention.

Fixed!
