### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by freekmurze** [spatie/image-optimizer#104]
This should be fixed.

**Comment by rubenvanassche** [comment]
As long as this issue keeps existing(https://github.community/t5/GitHub-Actions/ubuntu-latest-Apt-repository-list-issues/td-p/41122) we cannot use Github Actions 😢. Will check on this again next week

**Comment by rubenvanassche** [comment]
There is still a problem 😢, we're using the `danmbox/ppa` for the optimizer dependencies but it is only released for Ubuntu 14.04 (which Travis uses for some reason). We can only use 16.04 and 18.04 on GitHub Actions. A solution would be to create a docker container but that may bring us too far ...
