### ISSUE TITLE
Slow compression

### ISSUE THREAD

**Issue by maganius** [spatie/image-optimizer#105]
I installed this library with Laravel 6 and the compression time is a quite slow, between 25 and 40 seconds per image.
I have some question about it.

- Its normal?
- I need compress the images with a task?
- What impact have the server if I make it in a task, the website will be affected?
- Whats the recommended CPU/Ram specs?

The site have a dropzone where each client can upload a max of 300 photos, I want optimize the images to save disk space and gain page speed on browser image load.

Its my local specs

Intel(R) Core(TM)2 CPU          6400  @ 2.13GHz
MemTotal:         957408 kB
MemFree:           88340 kB
MemAvailable:     115412 kB

**Comment by freekmurze** [comment]
I guess the performance should be much much better. Unfortunately I have no time to look into server specific issues.

If the package can be improved to fix this, please submit a PR
