### ISSUE TITLE
optimizer Image got larger than original

### ISSUE THREAD

**Issue by odaiderawi** [spatie/image-optimizer#107]
![image](https://user-images.githubusercontent.com/36736057/71364590-55f25d80-25a5-11ea-9fe9-39ec50f6a622.png)

original 112k
optimizer 190k !!

**Comment by freekmurze** [comment]
Probably this is caused by something in your environment. Please provide a test for us to fix.

**Comment by mathmul** [comment]
I find [Image Compressor](https://imagecompressor.com/) gives *best* results for manual optimization. And if the image is already optimized with this (or some other) tool, then `new Image('image.min.png')->quality(75)->save();` (Forgive me to go out of scope with a wrapping package) will AFAIK always result in a byte-wise bigger picture.

Different algorithms by the looks of it. 

Despite this, I know of no better tool than spatie/image-optimizer (spatie/image, spatie/browsershot), to optimize images uploaded by users who take pictures with their phones/cameras and don't know how to resize and optimize them.
