### ISSUE TITLE
file

### ISSUE THREAD

**Issue by masoodsajedi** [spatie/image-optimizer#113]
![image](https://user-images.githubusercontent.com/14310899/78866053-f33da880-7a53-11ea-9bdb-4bfec09f2ed2.png)

file exist but return does not exist 
my code :
![image](https://user-images.githubusercontent.com/14310899/78866168-23854700-7a54-11ea-96b5-de4a54aa8e03.png)

**Comment by neok** [comment]
check that `is_file($pathToImage)`, if it's not then you are doing something wrong.
