### ISSUE TITLE
Apple HEIC support

### ISSUE THREAD

**Issue by pultho** [spatie/image-optimizer#116]
Any chance to get support for [Apple's HEIC](https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format) format?

Maybe by building Imagick with [LIBHEIF](https://github.com/strukturag/libheif) support and converting them over to JPG?

**Comment by freekmurze** [comment]
I don’t have a need for this, so I’m not going to invest my time in it, but feel free to submit PRs that are tested and documented
