### ISSUE TITLE
phpdoc

### ISSUE THREAD

**Issue by LKDevelopment** [spatie/image-optimizer#12]
Hello,

you can understand this issue as a little question, i've tried to review your code and one thing is there, what i can't understand :) Why you don't use phpdoc ? It would be much better, especially for IDE Support. 

Thank you for all your work!

**Comment by freekmurze** [comment]
I don't use a docblock if all the typehints already give the info on types you'll need.

Could you point me to a method where you feel a docblock would be beneficial?

**Comment by freekmurze** [comment]
Closing this for now, feel free to reopen.
