### ISSUE TITLE
Docs: Supported pngquant version

### ISSUE THREAD

**Issue by ybc37** [spatie/image-optimizer#120]
Hey there,

I already commented on a closed issue (https://github.com/spatie/image-optimizer/issues/97#issuecomment-680140810), but not sure someone read this, so I hope it's okay to open a new issue :)

I think there's a mismatch between the docs and the actual situation with the supported version of `pngquant`. There was an issue with `pngquant`, but AFAIU, at the end it wasn't related to the `pngquant` version (see #97). But the readme still states:

> This package only supports Pngquant 2.5 and lower.

Even worse, also projects relying on this one, spread this information, see https://github.com/TypistTech/image-optimize-command#optimization-tools

Am I right that the issue was only with packaging on Cent OS/RH? If so, the warning should be removed again. I'm happy to prepare a pull request (also for TypistTech/image-optimize-command) :)

**Comment by freekmurze** [comment]
Feel free to PR improvements.
