### ISSUE TITLE
New tag version ?

### ISSUE THREAD

**Issue by smknstd** [spatie/image-optimizer#121]
Would love to try the new quality config parameter (https://github.com/spatie/image-optimizer/pull/109) and if I'm not wrong it is not available in any tagged version. 

Have you consider making it a parameter in https://github.com/spatie/image/blob/master/src/Image.php#L148 (and then spatie/laravel-medialibrary) as well ?

**Comment by freekmurze** [comment]
The PR is from long ago, I'm pretty sure we have tagged this package after that. 

Didn't need that parameter myself so made no further integrations with medialib.

**Comment by smknstd** [comment]
sorry to bother @freekmurze, but I think last tagged version is 1.2.1 : https://packagist.org/packages/spatie/image-optimizer

and I don't see the new config parameter here:

https://github.com/spatie/image-optimizer/blob/1.2.1/src/OptimizerChainFactory.php#L14

compared to master:

https://github.com/spatie/image-optimizer/blob/master/src/OptimizerChainFactory.php#L14

**Comment by freekmurze** [comment]
You're right! I'll create a new tag for this. Thanks for bringing this to my attention.

**Comment by smknstd** [comment]
👍
