### ISSUE TITLE
Possible issue with Gifsicle

### ISSUE THREAD

**Issue by ti0rafa** [spatie/image-optimizer#130]
Hello, I was testing this library to optimize some GIFs and I think I found something wrong.

I setup the optimizer with the following parameters:
```
$OptimizerChain = new OptimizerChain();
$OptimizerChain->useLogger($Logger);
$OptimizerChain->addOptimizer(new Gifsicle([
    '-O3',
    '--lossy=20'
]));
```

After running some test using this library I noticed that file sizes stay the same. I wanted to make sure this was right so I ran `gifsicle` manually but file sizes did shrink, so there was something wrong.

My next step was to see how this library build the command VS the command I was using.

This library builds the command like:
```
"gifsicle" -O3 --lossy=20 'my.gif'
```
Looking at monolog, a bunch of binary data is return which is probably wrong.

Copy and pasting the command how the library builds, it outputs:
```
gifsicle:<stdout>: Is a terminal: try `-o OUTPUTFILE`
```

The manual test I did was using the following command:
```
"gifsicle" -O3 --lossy=20 -i 'my.gif' -o 'my.gif'
```

So I modified the following file `\Spatie\ImageOptimizer\Optimizers\Gifsicle` with the following code:
```
public function getCommand(): string
{
    $optionString = implode(' ', $this->options);

    return "\"{$this->binaryPath}{$this->binaryName}\" {$optionString}"
        .' -i '.escapeshellarg($this->imagePath)
        .' -o '.escapeshellarg($this->imagePath);
}
```

Having it this way does make running this library make those GIFs files smaller.

The versions im using are: 
- gifsicle `1.92`
- php `7.3.11` 
- macOS `10.15.7`

**Comment by freekmurze** [comment]
Thanks for investigating this. Could you send a PR with the fix?
