### ISSUE TITLE
Add support for --skip-if-larger option of pngquant

### ISSUE THREAD

**Issue by MrPropre** [spatie/image-optimizer#139]
Hi,

I think `image-optimizer` has been created to make the new image size smaller than the original image size. So if the size is bigger, we should just keep the original image intact. pngquant supports this behavior by simply adding the `--skip-if-larger` option.

> If conversion results in a file larger than the original, the image won't be saved and pngquant will exit with status code Er 98 . Additionally, file size gain must be greater than the amount of quality lost. If quality drops by 50%, it will expect 50% file size reduction to consider it worthwhile.`

Thank you in advance!

**Comment by freekmurze** [comment]
Feel free to PR this to the package!

**Comment by MrPropre** [comment]
@freekmurze Done! #140
