### ISSUE TITLE
Overriding binaries

### ISSUE THREAD

**Issue by david-ridgeonnet** [spatie/image-optimizer#19]
Hello,

Would it be possible to use a configuration file to specify the binaries or something? Currently these are coded into each class as something that's expected to be in the PATH for either windows/*nix users.

It would be helpful to be able to override it.

Thanks

**Comment by freekmurze** [comment]
Could you give me an example of what the ideal way of overriding the binaries would look to you?

**Comment by david-ridgeonnet** [comment]
I guess it can just be changed directly on the optimiser classes as the `$binaryName` is public...

An example of another library that uses binaries but allows overriding from the configuration is: https://github.com/barryvdh/laravel-snappy

This allows me to override it with an `env()` call to load it from the `.env` and provide a sensible default too. That way when it's running on a Windows machine, I specify the different binary otherwise I do not specify it on linux machines.

Does that clarify?

**Comment by freekmurze** [comment]
I'm not going to add functions that readme the environment to this package. You can easily build up your own optimizer chains. The included factory contains an example on how to do that

https://github.com/spatie/image-optimizer/blob/master/src/OptimizerChainFactory.php

On each optimizer you can set the binary path manually.

I'm currently toying with the idea of creating a laravel wrapper that does read env variables and more...
