### ISSUE TITLE
Exception - Class Spatie\ImageOptimizer\InvalidArgumentException not found

### ISSUE THREAD

**Issue by MarekGogol** [spatie/image-optimizer#217]
Hello,

I've got following exception in production. You probably forgot to import namespace in OptimizerChain.php . Bug is present from 1.7.3 version.

<img width="874" alt="image" src="https://github.com/spatie/image-optimizer/assets/11134410/b04baa8a-f58f-4c7c-b6cb-ea63ad432971">

Check:
https://github.com/spatie/image-optimizer/commit/89847b55fbb44b3bcde0283bff8cc5abb5e51b82#diff-bba71f2a0cdb3b9cd6b11fed0fe0f308b37c6adf7a2c1a8bd6cf18f44fd163e7

+ You should also check if $pathToImage is not equal to $pathToOutput and skip this whole if statement in that case. It may happen that those variables are the same, and you will get this exception. But you should not. Otherwise backward compatibility will be broken and developers will get unexpected error if second parameter will be same.

**Comment by freekmurze** [comment]
I've made a new release that imports that exception namespace.
