### ISSUE TITLE
Process errored with "sh: jpegoptim: command not found"

### ISSUE THREAD

**Issue by a3020** [spatie/image-optimizer#26]
Do you have any suggestions on what to do if this error occurs?

``` Process errored with `sh: jpegoptim: command not found`}```

macOS 10.12.6, PHP 7.1, Apache 2.4.

`brew list` shows `jpegoptim`.

If I open the terminal and enter `jpegoptim`, the command works as expected.

The same problem occurs for the other optimizers. Is there something wrong in my PHP configuration?

**Comment by a3020** [comment]
Update: I extracted the `proc_open` call to a test script. It works OK via CLI, but not via a browser. I then changed the command to `/usr/local/bin/jpegoptim` which made it work in both occassions. It's probably a path issue.

**Comment by a3020** [comment]
Fixed it by editing `/Library/LaunchDaemons/homebrew.mxcl.httpd24.plist` and adding:

```
<key>EnvironmentVariables</key>
<dict>
   <key>PATH</key>
   <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
</dict>
```

**Comment by MaximVanhove** [comment]
@a3020 I'm having the same issue, also using MAMP. I do not have the file homebrew.mxcl.httpd24.plist nor the folder LaunchDaemons. Any suggestions?

**Comment by a3020** [comment]
I'm not familiar with MAMP, but try StackOverflow, e.g. https://stackoverflow.com/questions/40767857/change-path-environment-variable-in-mamp

**Comment by MaximVanhove** [comment]
That did the trick!
