### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by jaapgoorhuis** [spatie/image-optimizer#27]
Hi,

When i try to install the package i get the following error.

PS C:\xampp\htdocs> composer require spatie/image-optimizer
Using version ^1.0 for spatie/image-optimizer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install spatie/image-optimizer 1.0.7
    - Conclusion: don't install spatie/image-optimizer 1.0.6
    - Conclusion: don't install spatie/image-optimizer 1.0.5
    - Conclusion: don't install spatie/image-optimizer 1.0.4
    - Conclusion: don't install spatie/image-optimizer 1.0.3
    - Conclusion: don't install spatie/image-optimizer 1.0.1
    - Conclusion: remove symfony/process v2.7.29
    - Installation request for spatie/image-optimizer ^1.0 -> satisfiable by spatie/image-optimizer[1.0.0, 1.0.1, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7].
    - Conclusion: don't install symfony/process v2.7.29
    - spatie/image-optimizer 1.0.0 requires symfony/process ^3.3 -> satisfiable by symfony/process[v3.3.0, v3.3.1, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6].
    - Can only install one of: symfony/process[v3.3.0, v2.7.29].
    - Can only install one of: symfony/process[v3.3.1, v2.7.29].
    - Can only install one of: symfony/process[v3.3.2, v2.7.29].
    - Can only install one of: symfony/process[v3.3.3, v2.7.29].
    - Can only install one of: symfony/process[v3.3.4, v2.7.29].
    - Can only install one of: symfony/process[v3.3.5, v2.7.29].
    - Can only install one of: symfony/process[v3.3.6, v2.7.29].
    - Installation request for symfony/process (locked at v2.7.29) -> satisfiable by symfony/process[v2.7.29].

Installation failed, reverting ./composer.json to its original content.

i use laravel: 5.1

**Comment by freekmurze** [comment]
The error message is right. The package needs symfony/process 2.7 (or something from version 3) and the dependencies of your project do not allow that.

**Comment by jaapgoorhuis** [comment]
Thank you.
I just updated my laravel project from 5.1 to 5.2 and now i am able to install the package.

**Comment by freekmurze** [comment]
Pro tip: upgrade it to Laravel 5.4 😄
