### ISSUE TITLE
Quality reduction for Google Page Speed

### ISSUE THREAD

**Issue by barryvdh** [spatie/image-optimizer#29]
With the default settings, Google is not always happy with the result. Setting it to `-m85` (max quality 85%) does fix it according to https://webmasters.stackexchange.com/questions/102094/google-pagespeed-how-to-satisfy-the-new-image-compression-rules and my small experiment.

Would this be a good default? Or should we create a factory that is more aggressive?

**Comment by freekmurze** [comment]
Even though it could be considered as a breaking change, I'm willing to accept a PR that lowers the max quality to appease Google 😄

**Comment by barryvdh** [comment]
Did you encounter this issue yourself? Should I just add `-m85`?

**Comment by freekmurze** [comment]
Meanwhile I've tagged a version with `-m85` myself (also included that PR for Symfony 2 you've just sent).

**Comment by barryvdh** [comment]
Ah cool, I was just checking the differences. I've tested with a sample image, with m90 it was still not happy, so m85 seems to work for me at least :)

Thanks!
