### ISSUE TITLE
Not changing size?

### ISSUE THREAD

**Issue by NathnC** [spatie/image-optimizer#32]
Hey having some trouble, doesn't seem to be changing my file size, original is 761kb and fixed is still 761kb

On one of my controllers:

`use Spatie\ImageOptimizer\OptimizerChainFactory;`

`$pathToOptimizedImage = 'images/uploads/fixed.png';
        $pathToImage = 'images/uploads/download.png';
        $optimizerChain = OptimizerChainFactory::create();
        $optimizerChain
            ->optimize($pathToImage, $pathToOptimizedImage);`

**Comment by freekmurze** [comment]
Make sure the necessary binaries (described in the readme) are present on your system.

You can [add some logging](https://github.com/spatie/image-optimizer#logging-the-optimization-process) to check what the package is doing.

**Comment by NathnC** [comment]
Thank you, slight question, are there no binaries for windows? Currently hosting it locally atm and I often switch between my mac and pc

**Comment by freekmurze** [comment]
I'm not a windows user, so can't help you there 😄
