### ISSUE TITLE
Macos PHP71 doesn't work

### ISSUE THREAD

**Issue by dronni3de** [spatie/image-optimizer#33]
Hi guys!
How can your lib be working in php71 on MacosX?
Right now i've got an error:

`Fatal error: Uncaught Symfony\Component\Process\Exception\RuntimeException: The process has been signaled with signal "6". in /Users/andrejbastrikin/Documents/Projects/JonCooper/iPropertyManagement/wp/vendor/symfony/process/Process.php:431 Stack trace: #0 /Users/andrejbastrikin/Documents/Projects/JonCooper/iPropertyManagement/wp/vendor/symfony/process/Process.php(216): Symfony\Component\Process\Process->wait() #1 /Users/andrejbastrikin/Documents/Projects/JonCooper/iPropertyManagement/wp/vendor/spatie/image-optimizer/src/OptimizerChain.php(101): Symfony\Component\Process\Process->run() #2 /Users/andrejbastrikin/Documents/Projects/JonCooper/iPropertyManagement/wp/vendor/spatie/image-optimizer/src/OptimizerChain.php(77): Spatie\ImageOptimizer\OptimizerChain->applyOptimizer(Object(Spatie\ImageOptimizer\Optimizers\Jpegoptim), Object(Spatie\ImageOptimizer\Image)) #3 /Users/andrejbastrikin/Documents/Projects/JonCooper/iPropertyManagement/wp/wp-content/themes/ipropertymanagement/header.php(40): Spatie\ImageOptimizer\OptimizerChai in /Users/andrejbastrikin/Documents/Projects/JonCooper/iPropertyManagement/wp/vendor/symfony/process/Process.php on line 431`

Can you please let me know why this is happening? Just followed your guide.

**Comment by freekmurze** [comment]
I believe the error message signifies that the binaries this package uses are not installed properly.
