### ISSUE TITLE
Error executing commands on windows

### ISSUE THREAD

**Issue by n3vrax** [spatie/image-optimizer#35]
it seems placing the binary name between single quotes does not work, at least on windows
it gives command not found

```php
public function getCommand(): string
{
    $optionString = implode(' ', $this->options);
    return "'{$this->binaryName}' {$optionString} ".escapeshellarg($this->imagePath);
}
```

Maybe should stick to double quotes instead, that seem to work on the command line

**Comment by n3vrax** [comment]
opened a pull request #36

**Comment by freekmurze** [comment]
We'll handle this further in #36
