### ISSUE TITLE
Problem when install image-optimizer Conclusion: don't install spatie/image-optimizer 1.0.9

### ISSUE THREAD

**Issue by congloi** [spatie/image-optimizer#37]
here is error:

composer require spatie/image-optimizer

Using version ^1.0 for spatie/image-optimizer
./composer.json has been updated
> php artisan clear-compiled

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install spatie/image-optimizer 1.0.9
    - Conclusion: don't install spatie/image-optimizer 1.0.8
    - Conclusion: don't install spatie/image-optimizer 1.0.7
    - Conclusion: don't install spatie/image-optimizer 1.0.6
    - Conclusion: don't install spatie/image-optimizer 1.0.5
    - Conclusion: don't install spatie/image-optimizer 1.0.4
    - Conclusion: don't install spatie/image-optimizer 1.0.3
    - Conclusion: don't install spatie/image-optimizer 1.0.1
    - Installation request for spatie/image-optimizer ^1.0 -> satisfiable by spatie/image-optimizer[1.0.0, 1.0.1, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9].
    - Conclusion: remove symfony/process v2.7.5
    - spatie/image-optimizer 1.0.0 requires symfony/process ^3.3 -> satisfiable by symfony/process[v3.3.0, v3.3.1, v3.3.10, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9].
    - Can only install one of: symfony/process[v3.3.0, v2.7.5].
    - Can only install one of: symfony/process[v3.3.1, v2.7.5].
    - Can only install one of: symfony/process[v3.3.10, v2.7.5].
    - Can only install one of: symfony/process[v3.3.2, v2.7.5].
    - Can only install one of: symfony/process[v3.3.3, v2.7.5].
    - Can only install one of: symfony/process[v3.3.4, v2.7.5].
    - Can only install one of: symfony/process[v3.3.5, v2.7.5].
    - Can only install one of: symfony/process[v3.3.6, v2.7.5].
    - Can only install one of: symfony/process[v3.3.7, v2.7.5].
    - Can only install one of: symfony/process[v3.3.8, v2.7.5].
    - Can only install one of: symfony/process[v3.3.9, v2.7.5].
    - Installation request for symfony/process == 2.7.5.0 -> satisfiable by symfony/process[v2.7.5].

Installation failed, reverting ./composer.json to its original content.

"php": ">=5.5.9",
 "laravel/framework": "5.1.*",

can you down support for laravel 5.1, thank

**Comment by freekmurze** [comment]
If you need L5.1 support, fork the package and maintain your own compatible copy.
