### ISSUE TITLE
This code error

### ISSUE THREAD

**Issue by thanhansoft** [spatie/image-optimizer#42]
Please help me. Code this error
File: src/OptimizerChainFactory.php
line 13: public static function create(): **OptimizerChain**

**Comment by freekmurze** [comment]
I don't see an error in your issue report.

But my guess would be that you didn't install PHP 7 which is required for this package.

**Comment by reidsci** [comment]
I've been running into a problem on the same line and get this error:

Fatal error: Uncaught Error: Class 'Spatie\ImageOptimizer\OptimizerChainFactory' not found in D:\xampp\htdocs\playnow\testnow.php:8 Stack trace: #0 {main} thrown in D:\xampp\htdocs\playnow\testnow.php on line 8

The testnow.php file is as follows:
```
<?php

use Spatie\ImageOptimizer\OptimizerChainFactory;

$optimizerChain = OptimizerChainFactory::create();  // This is line 8 in my code

$pathToImage = 'images/myimage.php';

$optimizerChain->optimize($pathToImage);
```
PHP version is 7.2.2

I am new to PHP, but not to coding nor to putting in effort to solve my own problems. If you could give me a hint I will fight with it from there. I have fought with this for a while and am grasping at straws at this point on this problem.
