### ISSUE TITLE
Laravel 5.1 compatibility

### ISSUE THREAD

**Issue by 4rn0** [spatie/image-optimizer#48]
Great work on this package guys! I absolutely love it!

I'd really like to use it in a Laravel 5.1 LTS project I'm working on, but I can't because of the dependencies. Laravel 5.1 uses symfony/process 2.7.* while image-optimizer requires ^2.8.

Is there any way ^2.7 could be added to be compatible with 5.1? Or would that break stuff on your end?

**Comment by freekmurze** [comment]
We don't use L5.1

Feel free to invest your time in forking our code and maintaining a L5.1 compatible version.
