### ISSUE TITLE
Issue on Azure

### ISSUE THREAD

**Issue by soltmar** [spatie/image-optimizer#53]
Package fails on Azure due to some unknown problem with "Symfony\Process".

Unfortunately the only message which I'm getting is 
`The page cannot be displayed because an internal server error has occurred.`

Nothing in the Azure IIS and PHP logs.

Not sure what to suggest but maybe some detection that if on Azure / Windows then simply run "exec" instead of creating "Process" instance.

**Comment by freekmurze** [comment]
Going to leave things as they are for now. Please for the package and modify it to fit your needs.
