### ISSUE TITLE
Gist available for bulk recursive image optimization

### ISSUE THREAD

**Issue by migliori** [spatie/image-optimizer#54]
Hello,

Thanks for your wonderful image optimizer. No bug, it works like a charm.

I created this GIST to make a recursive bulk image optimization with image-optimizer: [https://gist.github.com/migliori/69e86e5ec6488c73c50d7f87fdd207db](https://gist.github.com/migliori/69e86e5ec6488c73c50d7f87fdd207db)

The optimization is made from a parent images folder. It optimizes all the images found recursively in all its subdirecories without deph limitation.

A single click launches the process. All is done with Ajax.
Tested with 5000+ images, optimized successfully in a few minutes.

I thought it may be useful for other users.

**Comment by freekmurze** [comment]
Thanks!
