### ISSUE TITLE
Parse error syntax error unexpected ?

### ISSUE THREAD

**Issue by bggcs** [spatie/image-optimizer#55]
OS Ubuntu 16.04
PHP Version 7.1.16
Web Server Nginx 1.10.3

My code
```
<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);

require_once 'vendor/autoload.php';

use Spatie\ImageOptimizer\OptimizerChainFactory;

$optimizerChain = OptimizerChainFactory::create();

$pathToImage = "test.jpg";
$pathToOutput = "test_1.jpg";

$optimizerChain->optimize($pathToImage, $pathToOutput);
?>
```

It appears error

Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /var/www/html/opt/vendor/symfony/process/Process.php on line 139

what can I do?

**Comment by freekmurze** [comment]
Probably you don't have the right php version in one of your environments.

Perform `phpinfo()` in a web request and in a script executed from the command line.
