### ISSUE TITLE
Optimizes images locally, but not in production?

### ISSUE THREAD

**Issue by kylescousin** [spatie/image-optimizer#59]
I have jpegoptim installed on the server, but it's not doing anything.

Is there anything else that needs to be installed in order for this to work? Could there be a permission issue?

The server is running CentOS.

**Comment by freekmurze** [comment]
Probably a permissions issue at your end. The tests of this package are running perfectly. Try [logging the optimization process](https://github.com/spatie/image-optimizer#logging-the-optimization-process) to get a hint of what's going wrong.
