### ISSUE TITLE
I do not see the image is optimized

### ISSUE THREAD

**Issue by thanhansoft** [spatie/image-optimizer#60]
Hi admin,
I use file image at for test . I do not see it reduced in size (optimizer). Please help me
`<?php 
include('vendor/autoload.php');
use Spatie\ImageOptimizer\OptimizerChainFactory;
$optimizerChain = OptimizerChainFactory::create();

$pathToImage = 'C:\xampp\htdocs\image\1.png';
$test = $optimizerChain->optimize($pathToImage);`

**Comment by freekmurze** [comment]
The readme has instruction on how to log the optimization process. Please make sure you've installed the necessary binaries and you can call them from PHP.

**Comment by thanhansoft** [comment]
Please help me install php binaries on windows using XAMPP.
