### ISSUE TITLE
copy() failed to open stream no such file or directory warning on server

### ISSUE THREAD

**Issue by vishuB** [spatie/image-optimizer#63]
copy() failed to open stream no such file or directory warning on server.
on localhost work perfect

Ubuntu: 16.04 LTS
PHP: PHP 7.1.19-1+ubuntu16.04.1+deb.sury.org+1 (cli)
Server version: Apache/2.4.18 (Ubuntu)

show below image
![image-optimizer issue](https://user-images.githubusercontent.com/13677102/42726808-06f4e37e-87b8-11e8-89f2-3df58c646a30.png)

**Comment by freekmurze** [comment]
This error is probably caused because you didn't set the right permissions for some directories

Dump the values of `$pathToImage` and `$pathToOutput`. Make sure that the php process has the right permissions to read and write files in those directories.
