### ISSUE TITLE
Image Not Comprime

### ISSUE THREAD

**Issue by MwSpaceLLC** [spatie/image-optimizer#71]
hi , this is my code : 
    $files = scandir('_xeo/_opt/');
        foreach($files as $file) {
        $optimizerChain = OptimizerChainFactory::create();
        $optimizerChain->optimize($file);    
          var_dump($optimizerChain);
        }
the images that are within the cycle, weigh like the original ones, do not understand why, the class seems to be loaded correctly.
the packages have been installed inside the server but we do not understand why this library is still not working, waiting for an answer Sincerely 👍

**Comment by MwSpaceLLC** [comment]
so, we tried to run the command via ssh, compression works so we do not understand why in PHP it does not run and it does not communicate any error.

ssh work perfect:
jpegoptim --strip-all * 
optipng _xeo/_opt/*

**Comment by freekmurze** [comment]
[Our tests](https://github.com/spatie/image-optimizer/blob/master/tests/OptimizerChainTest.php) seem to indicate that our code is working as intended. Probably you problem is caused by something server related.
