### ISSUE TITLE
Should we require `ext-fileinfo`?

### ISSUE THREAD

**Issue by TangRufus** [spatie/image-optimizer#76]
Should we require `ext-fileinfo` via composer.json?

Because [`mime_content_type()`](http://php.net/manual/en/function.mime-content-type.php) comes from the [File Information](http://php.net/manual/en/book.fileinfo.php) extension. 

https://github.com/spatie/image-optimizer/blob/2ce6e4f2a4b152e59d062edac63aa923f95b78af/src/Image.php#L22

Related: https://github.com/TypistTech/image-optimize-command/issues/31

**Comment by freekmurze** [comment]
Feel free to send a PR.
