### ISSUE TITLE
Amazon Linux EC2 Support? 

### ISSUE THREAD

**Issue by timothymarois** [spatie/image-optimizer#77]
Due to the requirement of `jpegoptim` EC2 Amazon Linux distro doesn't have this. And it's not part of their package of yum installs. Doing manually can't happen because it also requires a newer version of `libjpeg` which it believes is already on the latest version in the distro. I was not able to successfully get this working due to `jpegoptim` issues.

**Comment by freekmurze** [comment]
You can create your [own custom optimizer](https://github.com/spatie/image-optimizer#writing-a-custom-optimizers) for a tool that is included on EC2.
