### ISSUE TITLE
TinyPNG integration

### ISSUE THREAD

**Issue by jessedobbelaere** [spatie/image-optimizer#8]
This might be a bit too soon, but wanted to check if it's a good idea to **integrate external services too**. Let's say you don't have the necessary optimizers installed on the system, but you can still have the option to add your api key and let TinyPNG/TinyJPG optimize the images. 

I'm currently using their developer api in a CMS image optimization module I wrote, but would love to swap the custom code out by your library so I can also support the other system optimizers if there are any on the system, and I believe many others would benefit from TinyPNG too. 

With TinyPNG you get 500 images for free which is plenty for most of my use cases (and other users) + They do a really good job on compression (and can even crop/resize and do area-of-interest detection but that's not the goal of this package).

* [TinyPNG](https://tinypng.com/) & [TinyJPG](https://tinyjpg.com/)
* [Developer API](https://tinypng.com/developers) -> gets you an API token based on email address.
* This composer package might be useful to wrap the methods and integrate it: https://packagist.org/packages/tinify/tinify

**Comment by freekmurze** [comment]
Thanks for your suggestion. My aim for this package is that it requires zero setup (apart from the installation of some binaries) and is hassle free.

External services are a bit more complicated to work with:
- they need to be setup (API key is needed)
- they could cause significant slowdowns (image big images being uploaded over a slow connection to the service)
- the external service may be down

So I'm going to hold of including such optimizers by default for now. 

What you could do is create a separate package that handles optimization with TinyPng. It could contain a class that implements `Spatie\ImageOptimizer\Optimizer`.  More info on that here: https://github.com/spatie/image-optimizer#writing-a-custom-optimizers

If you do that, I would probably reference your package in the readme of this one.

**Comment by freekmurze** [comment]
Closing this for now, but if you have any questions or remarks, feel free to reopen.

**Comment by jessedobbelaere** [comment]
Ok thanks! I'll try making a custom optimizer library when I start the rewrite of my CMS module. I really like their compression rate, and although being a lossy compression, the compression not visible. 

There's the aspect of dealing with the API key, the limit of 500 images for a free account, and service possibly being down but depends on the project if you can afford having that. If down, I can even fall back on the system optimizers 🤔

E.g. the image from the readme (547kB)
The image after TinyJPG **(238.5 KB, -56%)**

![68747470733a2f2f7370617469652e6769746875622e696f2f696d6167652d6f7074696d697a65722f6578616d706c65732f696d6167652e6a7067 1](https://user-images.githubusercontent.com/1352979/27901314-e379a148-6231-11e7-9243-a528e5694502.jpeg)

**Comment by freekmurze** [comment]
That's a pretty good result.

It would be really awesome if that driver would just work in the current setup of this package (aka that it can be run from the command line).

Looking forward to your work on this.

**Comment by jeroendesloovere** [comment]
Would indeed be a nice module for our [Fork CMS](https://www.fork-cms.com).

**Comment by fiinix** [comment]
Hi, I know this is an older issue but I just wanted to bring up that TinyPNG uses pngquant as its main optimization library, which this already has
