### ISSUE TITLE
Should we considered with `imagedestroy`?

### ISSUE THREAD

**Issue by nmfzone** [spatie/image-optimizer#90]
In the [Laravel's queue documentation](https://laravel.com/docs/5.8/queues#running-the-queue-worker) (in `Resource Consideration`), it's mention that we should perform `imagedestroy` after optimizing the image, when we're using queue.

> Daemon queue workers do not "reboot" the framework before processing each job. Therefore, you should free any heavy resources after each job completes. For example, if you are doing image manipulation with the GD library, you should free the memory with imagedestroy when you are done.

Should the `imagedestroy` implemented by default in this package?

**Comment by freekmurze** [comment]
Yeah, maybe we should. Feel free to PR improvements around this. I assume you should target spatie/laravel-medialibrary. Thanks!

**Comment by nmfzone** [comment]
@freekmurze Since not everyone using `spatie/laravel-medialibrary`, I believe I should target this package. B/c the optimization is handled by this package.

**Comment by freekmurze** [comment]
You're right. Go ahead!
