### ISSUE TITLE
PHP 7.0 --> PHP 7.2 dependency in a patch version

### ISSUE THREAD

**Issue by wilkinsocks** [spatie/image-optimizer#91]
v1.1.4 requires PHP 7.0 as a dependency, whereas v.1.1.5 requires PHP 7.2 so we got a Composer dependency error when updating Composer.

Was this an intentional update?

**Comment by riasvdv** [comment]
This was intentional. Upping requirements is not a breaking change according to semver. The public API did not change. For more info, please read the semver specification (https://semver.org/).
