### ISSUE TITLE
wp image-optimize find /path/to/my/directory --extensions=gif,jpeg,jpg,png,svg

### ISSUE THREAD

**Issue by gfrow** [spatie/image-optimizer#92]
I've tried every way I can think of to get this command to work:

wp image-optimize find /path/to/my/directory --extensions=gif,jpeg,jpg,png,svg

but I keep getting the fatal error. 

I'm using Xampp on PC. all other commands seem to work, but this one... no luck. Is there some trick to setting the file path that I'm missing?

**Comment by TangRufus** [comment]
Did you mean to create an issue on https://github.com/TypistTech/image-optimize-command/ ?

**Comment by freekmurze** [comment]
Seems like the issue is unrelated to this repo.
