### ISSUE TITLE
'jpegoptim' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by tv78-coder** [spatie/image-optimizer#94]
I have the following error in my log:

`[2019-09-17 19:17:01] optimize_error.ERROR: Process errored with '"jpegoptim"' is not recognized as an internal or external command, operable program or batch file.  [] []`

And i follow the documentation to use this optimizer:

```
$optimizerChain = OptimizerChainFactory::create();

$optimizerChain
  ->useLogger(new Logger('optimize_error'))
  ->optimize($file->getPathName());
```

I can execute jpegoptim command in my cmd but not in php..

I am using window 10 x64bit and xampp.

Any solution?

**Comment by tv78-coder** [comment]
Solved.

Forgot to restart computer after set path variable.

**Comment by hirwinnocent** [comment]
How you handled this issues, I still get this error : 
`[2021-05-30 19:39:35] local.ERROR: Process errored with `'"jpegoptim"' is not recognized as an internal or external command,
operable program or batch file.
`  `

**Comment by hirwinnocent** [comment]
> Solved.
> 
> Forgot to restart computer after set path variable.

How you handled this issues, I still get this error :
[2021-05-30 19:39:35] local.ERROR: Process errored with '"jpegoptim"' is not recognized as an internal or external command,
operable program or batch file.

**Comment by fd6130** [comment]
It is windows environment path issue, I just simply set a path and then restart my pc then it works.
